#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/utils"
source "$basedir/swift"

export PATH=${basedir}/../vendor/bin:$PATH

validate_env

#if [ -z "$S3_BUCKET" ]; then
#    echo "Must set S3_BUCKET environment variable" >&2
#    exit 1
#fi

tempdir="$(mktmpdir libmemcached)"
cd $tempdir

memcached_version=1.0.18

echo "-----> Downloading libmemcached"

curl -LO "https://launchpad.net/libmemcached/1.0/${memcached_version}/+download/libmemcached-${memcached_version}.tar.gz"
tar -xzvf "libmemcached-${memcached_version}.tar.gz"

pushd libmemcached-${memcached_version} >/dev/null && \
    mkdir -p /app/vendor/libmemcached && \
    ./configure --with-memcached=no --prefix=/app/vendor/libmemcached && \
    make && make install && popd > /dev/null

rm -r /app/vendor/libmemcached/share/man

mkdir package
pushd /app/vendor/libmemcached
tar zcvf ${tempdir}/package/libmemcached-${memcached_version}.tgz .
popd

#s3_path=s3://$S3_BUCKET/package/libmemcached-${memcached_version}.tgz

#echo "-----> Uploading package to ${s3_path}"

#s3cmd put --verbose \
#    --acl-public \
#    "$tempdir/libmemcached-${memcached_version}.tgz" \
#    "${s3_path}"

echo "-----> Uploading package to Swift"
swift_upload package/libmemcached-${memcached_version}.tgz

"$basedir/package-checksum" libmemcached-${memcached_version}

echo "-----> Done building libmemcached package!"
