#!/usr/bin/env bash

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

tempdir=$(mktmpdir composer)
cd $tempdir

curl -L http://getcomposer.org/composer.phar > composer.phar
md5 composer.phar > composer.phar.md5

mkdir composer
mv composer.phar composer
mv composer.phar.md5 composer

s3cmd put --verbose --acl-public \
    ./composer.phar s3://$S3_BUCKET/composer/composer.phar

s3cmd put --verbose --acl-public \
    ./composer.phar.md5 s3://$S3_BUCKET/composer/composer.phar.md5
