#!/usr/bin/env bash

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
#source "$basedir/utils"
#source "$basedir/swift"

tempdir=$(mktmpdir jq)
cd $tempdir

echo "----> Vendoring 'jq'"
curl -L http://stedolan.github.io/jq/download/linux64/jq > jq_bin

mkdir jq
mv jq_bin jq/jq
s3cmd put --verbose --acl-public ./jq s3://$S3_BUCKET/jq/jq

#swift_upload jq/jq