#!/usr/bin/env bash

set -e

download_url="http://download.icu-project.org/files/icu4c/51.2/icu4c-51_2-src.tgz"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$S3_BUCKET" ]; then
    echo "Must set S3_BUCKET environment variable" >&2
    exit 1
fi

tempdir=$(mktmpdir libicu)
cd $tempdir

curl -L "$download_url" | tar xzv \
  && mkdir -p /app/vendor/libicu \
  && pushd icu > /dev/null \
  && ./source/runConfigureICU Linux --prefix=/app/vendor/libicu \
  && make && make install \
  && popd > /dev/null

rm -r /app/vendor/libicu/share/man

mkdir package
pushd /app/vendor/libicu > /dev/null
tar zcvf "${tempdir}/package/libicu-51.tgz" .
popd > /dev/null

s3cmd put \
    --verbose --acl-public \
    "$tempdir/libicu-51.tgz" \
    "s3://$S3_BUCKET/package/libicu-51.tgz"

"$basedir/package-checksum" "libicu-51"
