#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

case "$1" in
detect)
    exit 1
    ;;
compile)
    echo "-----> Setting up Nginx configuration"
    cp "$basedir/../conf/nginx/default_site.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
    ;;
    end)
    echo "-----> Setting up opencart configuration"
  touch "$BUILD_DIR/config.php"
  touch "$BUILD_DIR/admin/config.php"
  chmod -R 777 "$BUILD_DIR/system/cache/"
  chmod -R 777 "$BUILD_DIR/system/logs/"
  chmod -R 777 "$BUILD_DIR/download/"
    ;;
esac
